#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# Change htaccess php settings to allow large file uploads
CONF=/etc/owncloud/htaccess
sed -i "s|php_value post_max_size.*|php_value post_max_size 10G|" $CONF
sed -i "s|php_value upload_max_filesize.*|php_value max_execution_time 1800\nphp_value max_input_time 1800\nphp_value upload_max_filesize 10G|" $CONF

